import { execSync, execFileSync } from "node:child_process";

export function pushBranch(cwd: string, branchName: string): void {
  execSync(`git push -u origin "${branchName}"`, { cwd, stdio: "pipe" });
}

export interface PRDetails {
  title: string;
  taskId: string;
  taskType: string;
  taskPriority: number;
  description: string;
  cliName: string;
  diffStat: string;
  criticScore?: number;
  criticIssues?: string[];
  testResults?: { passed: number; failed: number; skipped: number };
  typeCheckPassed?: boolean;
  costUsd?: number;
  tokensUsed?: number;
}

/**
 * Generate a concise PR title from task description.
 */
export function generatePRTitle(taskType: string, title: string): string {
  // Clean up title: remove common prefixes, truncate intelligently
  let cleaned = title
    .replace(/^(add|fix|update|refactor|improve|implement)\s+/i, "")
    .trim();

  // Capitalize first letter
  cleaned = cleaned.charAt(0).toUpperCase() + cleaned.slice(1);

  // Truncate at word boundary if too long
  if (cleaned.length > 60) {
    cleaned = cleaned.slice(0, 57).replace(/\s+\S*$/, "") + "...";
  }

  return `burn(${taskType}): ${cleaned}`;
}

/**
 * Build a rich PR body with diff stats, critic results, and test info.
 */
export function buildPRBody(details: PRDetails): string {
  const sections: string[] = [];

  // Task info
  sections.push(`## Task`);
  sections.push(`- **ID**: \`${details.taskId}\``);
  sections.push(`- **Type**: ${details.taskType}`);
  sections.push(`- **Priority**: ${details.taskPriority}`);
  sections.push(`- **CLI**: ${details.cliName}`);
  if (details.costUsd != null) {
    sections.push(`- **Cost**: $${details.costUsd.toFixed(2)}`);
  }
  if (details.tokensUsed != null) {
    sections.push(`- **Tokens**: ${details.tokensUsed.toLocaleString()}`);
  }
  sections.push("");

  // Description
  sections.push(`## Description`);
  sections.push(details.description);
  sections.push("");

  // Diff stats
  if (details.diffStat) {
    sections.push(`## Changes`);
    sections.push("```");
    sections.push(details.diffStat);
    sections.push("```");
    sections.push("");
  }

  // Critic review
  if (details.criticScore != null) {
    sections.push(`## Critic Review`);
    const scoreEmoji =
      details.criticScore >= 8 ? "🟢" :
      details.criticScore >= 6 ? "🟡" : "🔴";
    sections.push(`${scoreEmoji} **Score: ${details.criticScore}/10**`);
    if (details.criticIssues && details.criticIssues.length > 0) {
      sections.push("");
      sections.push("Issues found:");
      for (const issue of details.criticIssues) {
        sections.push(`- ${issue}`);
      }
    }
    sections.push("");
  }

  // Test results
  if (details.testResults) {
    const { passed, failed, skipped } = details.testResults;
    const testEmoji = failed === 0 ? "✅" : "❌";
    sections.push(`## Test Results`);
    sections.push(
      `${testEmoji} ${passed} passed, ${failed} failed${skipped > 0 ? `, ${skipped} skipped` : ""}`
    );
    sections.push("");
  }

  // Type check
  if (details.typeCheckPassed != null) {
    sections.push(
      `**TypeScript**: ${details.typeCheckPassed ? "✅ No errors" : "❌ Type errors detected"}`
    );
    sections.push("");
  }

  sections.push("---");
  sections.push("Generated by [burn-harness](https://github.com/bkmashiro/burn-harness)");

  return sections.join("\n");
}

export function createDraftPR(
  cwd: string,
  branchName: string,
  baseBranch: string,
  title: string,
  body: string,
  labels: string[] = []
): string {
  // Use execFileSync to avoid shell interpretation of body content
  // (backticks, $(), parentheses in PR body were being executed by /bin/sh)
  const args = [
    "pr", "create",
    "--base", baseBranch,
    "--head", branchName,
    "--title", title,
    "--body", body,
    "--draft",
  ];

  const url = execFileSync("gh", args, { cwd, encoding: "utf-8" }).trim();

  // Try to add labels (ignore failure — labels may not exist)
  if (labels.length > 0) {
    try {
      execFileSync("gh", ["pr", "edit", url, "--add-label", labels.join(",")], {
        cwd,
        stdio: "pipe",
      });
    } catch {
      // Labels don't exist on this repo — that's fine
    }
  }

  return url;
}

export function closePR(cwd: string, prUrl: string): void {
  try {
    execFileSync("gh", ["pr", "close", prUrl], { cwd, stdio: "pipe" });
  } catch {
    // ignore if already closed
  }
}
